// `.env.json` is generated by the `npm run build` command
import * as env from './.env.json';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://{API_SERVER_IP}:{API_SERVER_PORT}/blockchain',
  defaultLanguage: 'en-US',
  BANK_LIST: 'http://10.19.93.150:4100/app/mock-data/banklist.json',
  supportedLanguages: [
    'en-US',
    'fr-FR',
    'zh-CN'
  ]
};
